### ISSUE TITLE
Can't compile program

### ISSUE THREAD

**Issue by alirezacore** [vtorres/ragnarok-maya-purple#1]
Hi sir, i want to ask, why i failed when compile program, this is error.

error: failed to run custom build command for `ragnarok-maya-purple v1.0.0 (C:\xampp\htdocs\ragnarok-maya-purple-main)`

Caused by:
  process didn't exit successfully: `C:\xampp\htdocs\ragnarok-maya-purple-main\target\debug\build\ragnarok-maya-purple-ceb65bc8bf39c3ea\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', build.rs:11:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Is it possible to request that the compiled program be sent via email? Thank You

**Comment by vtorres** [comment]
The compiled version is here https://github.com/vtorres/ragnarok-maya-purple/releases/tag/v1.0.0
Do not forget to execute it as admin
