### ISSUE TITLE
NoDelay

### ISSUE THREAD

**Issue by P1X3LT0RCH** [vtorres/ragnarok-maya-purple#2]
Do you may have the pattern for nodelay or other stuff which is worth it? Ty in advance.

**Comment by vtorres** [comment]
@P1X3LT0RCH There are many ways, but it won't work on servers that use ADelays/NoDelay protection

But here it goes, the easiest way:

```
const NDL_OFFSET: usize = 0x009D545F;
let NDL_ORIGINAL_BYTES: Vec<u8> = vec![0xC6, 0x86, 0x9D, 0x00, 0x00, 0x00, 0x00, 0xC7];
let NDL_MODIFIED_BYTES: Vec<u8> = vec![0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xC7];
```

🏴‍☠️
